service: zweer-consumptive

plugins:
  - serverless-webpack
  - serverless-apig-s3

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack: ./config/webpack/config/serverless.js
  webpackIncludeModules:
    packagePath: ./package.json
  apigs3:
    dist: static-dist

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  helloWorld:
    handler: lambda/helloWorld.handle
    events:
      - http:
          path: api/helloWorld
          method: get
          cors: true
